[en]
title = "M0D4S's blog"
weight = 1
LanguageName = "EN"
contentDir = "content/english"

[ar]
title = "فلان الفلاني
description = "أن أعمل ك"
contentDir = "content/arabic" 
weight = 2
LanguageDirection = "rtl" 
LanguageName = "AR"
